version: "3.8"

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile.conversation
    image: my-flask-conversation-app
<<<<<<< HEAD
    # container_name: my-flask-conversation-container
=======
    #container_name: my-flask-conversation-container
>>>>>>> 3a50bb9ee1ea9f7e9c673852f833dda2d2db0c01
    env_file:
      - "${ENV_FILE_PATH}"

    networks:
      - app-network

  merge-flask:
    build:
      context: .
      dockerfile: Dockerfile.mergeflask
    image: my-merge-flask-app
    container_name: my-merge-flask-container
    env_file:
      - "${ENV_FILE_PATH}"

    networks:
      - app-network
  nginx:
    image: nginx:latest
    restart: on-failure
    ports:
      - "7999:80"
    volumes:
      - /etc/nginx/nginx2.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app

networks:
  app-network:
    name: app-network
    driver: bridge
